import React, { useEffect, useState } from 'react';
import { recommendationAPI } from '../services/api.js';
import DashboardLayout from '../layouts/DashboardLayout.jsx';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
import EmptyState from '../components/EmptyState.jsx';
import { BookOpen, Loader2, Bookmark, BookmarkCheck, RefreshCw, ExternalLink } from 'lucide-react';
import toast from 'react-hot-toast';

const difficultyColor = {
  beginner: 'bg-green-100 text-green-700',
  intermediate: 'bg-blue-100 text-blue-700',
  advanced: 'bg-purple-100 text-purple-700',
};

const typeColor = {
  course: 'bg-orange-100 text-orange-700',
  article: 'bg-sky-100 text-sky-700',
  video: 'bg-red-100 text-red-700',
  practice: 'bg-teal-100 text-teal-700',
};

const Recommendations = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const fetchRecommendations = async () => {
    setLoading(true);
    try {
      const res = await recommendationAPI.get();
      setRecommendations(res.data.recommendations);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const generateNew = async () => {
    setGenerating(true);
    try {
      const res = await recommendationAPI.generate({});
      setRecommendations(res.data.recommendations);
      toast.success('New recommendations generated by IBM Granite!');
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to generate recommendations';
      if (msg.includes('IBM') || msg.includes('configured')) {
        toast.error('IBM Granite not configured. Add credentials to server .env');
      } else {
        toast.error(msg);
      }
    } finally {
      setGenerating(false);
    }
  };

  const toggleSave = async (id) => {
    try {
      const res = await recommendationAPI.toggleSave(id);
      setRecommendations((prev) =>
        prev.map((r) => (r._id === id ? { ...r, isSaved: res.data.recommendation.isSaved } : r))
      );
    } catch (err) {
      toast.error('Failed to save');
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Learning Resources</h1>
            <p className="text-gray-500 text-sm mt-1">AI-curated recommendations by IBM Granite</p>
          </div>
          <button onClick={generateNew} disabled={generating} className="btn-primary flex items-center gap-2 text-sm">
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
            {generating ? 'Generating...' : 'Generate New'}
          </button>
        </div>

        {loading ? (
          <div className="flex justify-center py-16"><LoadingSpinner size="lg" /></div>
        ) : recommendations.length === 0 ? (
          <EmptyState
            icon={<BookOpen className="h-12 w-12 text-gray-300" />}
            title="No Recommendations Yet"
            description="Click 'Generate New' to get personalized learning resources from IBM Granite"
            action={
              <button onClick={generateNew} disabled={generating} className="btn-primary flex items-center gap-2">
                {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                Generate Recommendations
              </button>
            }
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {recommendations.map((rec) => (
              <div key={rec._id} className="card hover:shadow-md transition-all flex flex-col">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex gap-2 flex-wrap">
                    <span className={`badge text-xs ${difficultyColor[rec.difficulty] || 'bg-gray-100 text-gray-600'}`}>
                      {rec.difficulty}
                    </span>
                    <span className={`badge text-xs ${typeColor[rec.resourceType] || 'bg-gray-100 text-gray-600'}`}>
                      {rec.resourceType}
                    </span>
                  </div>
                  <button onClick={() => toggleSave(rec._id)} className="text-gray-400 hover:text-primary-600 transition-colors">
                    {rec.isSaved ? <BookmarkCheck className="h-4 w-4 text-primary-600" /> : <Bookmark className="h-4 w-4" />}
                  </button>
                </div>
                <h3 className="font-semibold text-gray-900 mb-1">{rec.title}</h3>
                <p className="text-xs text-primary-600 font-medium mb-2">{rec.topic}</p>
                <p className="text-sm text-gray-500 flex-1 leading-relaxed">{rec.reason}</p>
                {rec.estimatedTime && (
                  <p className="text-xs text-gray-400 mt-3">⏱ {rec.estimatedTime}</p>
                )}
                {rec.resourceUrl ? (
                  <a
                    href={rec.resourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-3 text-sm text-primary-600 hover:text-primary-700 font-medium flex items-center gap-1"
                  >
                    View Resource <ExternalLink className="h-3.5 w-3.5" />
                  </a>
                ) : (
                  <p className="text-xs text-gray-400 mt-3 italic">Search for this resource online</p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
};

export default Recommendations;
